### ISSUE TITLE
Save PrintData to file

### ISSUE THREAD

**Issue by iraddev** [eduardobogoni/jlibfprint#7]
Hi,
First of all I want to say thank you for your work! This is exactly what I searched for except this tiny problem:
I want to save enrollResult.getPrintData() to a local file for it to be used for the verify function (if I want to verify my fingerprint in a seperate program from my enroll function) but unfortunately java returns the following error:
> java.io.NotSerializableException: jlibfprint.PrintData
> 	at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1185)
> 	at java.base/java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:349)
> 	at auth.FingerprintTest.enroll(FingerprintTest.java:39)
> 	at auth.Authentication.run(Authentication.java:7)
> 	at MainTest.main(MainTest.java:15)

This is my current code:
```
import jlibfprint.*;
import java.io.*;
public class FingerprintTest extends Authentication {
    private Device device;

    public FingerprintTest() {
        DiscoveredDeviceList discoveredDeviceList = JlibFprint.discoverDevices();
        DiscoveredDevice firstDiscoveredDevice = getFirstDiscoveredDevice(discoveredDeviceList);
        if (firstDiscoveredDevice == null) {
            System.out.println("No device found to enroll fingers");
        } else {
            this.device = firstDiscoveredDevice.open();
        }
    }

    private static DiscoveredDevice getFirstDiscoveredDevice(DiscoveredDeviceList discoveredDeviceList) {
        return discoveredDeviceList.getDiscoveredDevices().length > 0
                ? discoveredDeviceList.getDiscoveredDevices()[0]
                : null;
    }

    public void enroll() {
        EnrollResult enrollResult = null;
        for ( int i = 0 ; i < this.device.getNumberEnrollStages() ; i++ ) {
            System.out.println("Please, enroll the finger");
            enrollResult = this.device.enroll();
            System.out.println("Enroll result code: " + enrollResult.getCode());
            if (!EnrollResultCode.PASS.equals(enrollResult.getCode()) && !EnrollResultCode.COMPLETE.equals(enrollResult.getCode())) {
                System.out.println("Enrollment Failed");
                return;
            }
        }
        try {
            String path = "src/main/resources/fingerprint/" + System.getProperty("user.name") + ".ser";
            FileOutputStream fileOut = new FileOutputStream(path);
            ObjectOutputStream objectOut = new ObjectOutputStream(fileOut);
            objectOut.writeObject(enrollResult.getPrintData());
            objectOut.close();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    public boolean verify() {
        try {
            String path = "src/main/resources/fingerprint/" + System.getProperty("user.name") + ".ser";
            ObjectInputStream oos = new ObjectInputStream(new FileInputStream(path));
            PrintData printData = (PrintData) oos.readObject();
            if (printData == null)
                throw new JlibFprint.EnrollException();
            System.out.println("Please, enroll the finger again to verify");
            VerifyResultCode result = this.device.verify(printData);
            device.close();
            return VerifyResultCode.MATCH.equals(result);
        } catch (JlibFprint.EnrollException e) {
            System.err.println("Enrollment hasn't been Completed");
        } catch (ClassNotFoundException | IOException e ) {
            System.err.println(e.getMessage());
        }
        this.device.close();
        return false;
    }
}
```
What can I do with this error?
Thanks in advance!

**Comment by eduardobogoni** [comment]
The exception is raised because jlibfprint.PrintData is not serializable. To do it you will have - probably - to work in C++ [counterpart](https://github.com/eduardobogoni/jlibfprint/blob/master/JlibFprint_jni/src/jlibfprint_PrintData.cpp) in project [JlibFprint_jni](https://github.com/eduardobogoni/jlibfprint/blob/master/JlibFprint_jni).

**Comment by iraddev** [comment]
Do you have an idea how I can make it serializable in java?
I saw something simillar in StackOverflow but just couldn't get the hang of it- https://stackoverflow.com/questions/95181/java-serialization-with-non-serializable-parts

Can you please help me?
